### ISSUE TITLE
Create array input parameter for "Collect All The Things!" Node

### ISSUE THREAD

**Issue by maxgraf96** [Interactml/iml-ue4#5]
Hi! 

First of all, thank you for your great work on this, I have been using it for the past few days and it's amazing! I have a quick question regarding input handling on the "Collect All The Things Node" - in the wiki it is mentioned that all data is internally represented as a float array, so would it be possible to add support for a float array input parameter? I have a collection of floats that come from hand joint data for each training sample, and don't know how to elegantly feed them into a training set in the current state.

Let me know what you think :)
Max

**Comment by samswain** [comment]
Yes, definitely, this is on the future to-do list.

Thanks for the feedback. I didn't know we have users yet 😄

Sam

P.S. The documentation is still WIP but should be at 'beta'/first pass stage in a week or so.  Marketplace release at some point soon too.

**Comment by maxgraf96** [comment]
Cool :) 

Yes, I stumbled upon it yesterday and it's pretty much exactly what I was looking for! Also, I managed to compile it for UE5EA, if you're interested I'll test it for the next few days and then submit a PR.

No worries about the documentation, it's really good so far :)

Max

**Comment by samswain** [comment]
UE5 is known to work, but we just don't list it as supported (yet). No code changes were required last time I tried it. Should just need the auto-packaging scripts to be updated and a new entry on the Marketplace product sheet for that engine version.
Ta.

**Comment by maxgraf96** [comment]
Ah nice! Looking forward to the official release 👍

**Comment by sam-apparance** [comment]
Parameter collection node now accepts arrays of any of the supported data types.
