### ISSUE TITLE
The demo project blueprint InteractML_MotionControlPawn won't compile...

### ISSUE THREAD

**Issue by owenbrierley-bit** [Interactml/iml-ue4#8]
Hi,

I am excited by the potential of InteractML! I am attempting to try some of the demos out, and I am hitting a snag. Everything seems to relate to the motion control pawn... I am attaching a portion of the errors that are showing. Hopefully it will be something obvious that I am missing. 

Any thoughts?

Kind regards,
Owen

![Capture](https://user-images.githubusercontent.com/58825893/167167387-1088636c-e664-407b-b116-fb0d3314ae47.PNG)

**Comment by sam-apparance** [comment]
For most of the demos you won't need the blueprints that are reporting problems so you can just edit them to disconnect the input execute wires of the erroring nodes (hold Alt and click/drag the wire).
I believe this is due to updates by Epic to Unreal engine.  Hopefully we'll be able to find time to fix these in the future.

**Comment by owenbrierley-bit** [comment]
Awesome! Thanks for the quick reply. :)

**Comment by owenbrierley-bit** [comment]
I can compile and run, now to delve into what it means. ;) 

May I ask a question about the Minimum Viable Demo here or do you want me to open a new issue? The project crashes when I try to record. I can post the log if that helps.

**Comment by sam-apparance** [comment]
Sure, sounds unusual, logs would help.  Please open a new issue though.  Thanks.

**Comment by owenbrierley-bit** [comment]
Well... I solved my own problem. (PEBKAC ;) ) It always helps to wire EVERYTHING from the provided examples. I was missing a link to the live parameters pin on the "machine learning robot." 1 out of 2 wires is not enough!
