### ISSUE TITLE
Expected Output float not connecting to Example Recorder Float pin (Unreal 5.0.1)

### ISSUE THREAD

**Issue by phoenixperry** [Interactml/iml-ue4#9]
In the event graph, if you create a float variable and attempt to assign it to the Example Recorder note parameter "expected output" it gives the following error, "Float (double precision) is not compatible with float." If you attempt to promote the expected output parameter to a variable and connected it, it gives you the following error, "Float (single precision) is not compatible with float."

**Comment by sam-apparance** [comment]
Ok, so, this issue was already fixed for some of the code/nodes, but a couple were missed. This should be fixed for the Recording and Running input pins that were reporting a reconnection issue.  See change: https://github.com/Interactml/iml-ue4/commit/2cbb7cfc21cd9c83eebf6720314791e24a32ffee

**Comment by phoenixperry** [comment]
Great, does this mean I should push a new build? Thanks in advance, Phoenix    From: Sam SwainSent: Sunday, May 22, 2022 4:36 PMTo: Interactml/iml-ue4Cc: Phoenix Perry; AuthorSubject: Re: [Interactml/iml-ue4] Expected Output float not connecting to Example Recorder Float pin (Unreal 5.0.1) (Issue #9) Ok, so, this issue was already fixed for some of the code/nodes, but a couple were missed. This should be fixed for the Recording and Running input pins that were reporting a reconnection issue. See change: 2cbb7cf—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
